import {COLORS} from './colors';

export const SPACING = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
};

export const FONT_SIZES = {
  xs: 11,
  sm: 13,
  md: 15,
  lg: 17,
  xl: 20,
  xxl: 24,
  xxxl: 32,
};

export const FONT_WEIGHTS = {
  regular: '400' as const,
  medium: '500' as const,
  semibold: '600' as const,
  bold: '700' as const,
};

export const BORDER_RADIUS = {
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  full: 999,
};

export type ThemeId =
  | 'theme1'
  | 'theme2'
  | 'theme3'
  | 'theme4'
  | 'theme5'
  | 'theme6'
  | 'theme7'
  | 'theme8'
  | 'theme9'
  | 'theme10'
  | 'theme11'
  | 'theme12'
  | 'theme13'
  | 'theme14'
  | 'theme15'
  | 'theme16'
  | 'theme17'
  | 'theme18'
  | 'theme19'
  | 'theme20';

export interface AppTheme {
  id: ThemeId;
  name: string;
  isDark: boolean;
  background: string;
  bgGradient: string[];
  primaryGradient: string[];
  buttonGradient: string[];
  cardBackground: string;
  primaryText: string;
  secondaryText: string;
  accent: string;
  border: string;
  inputBackground: string;
  statusBar: 'dark-content' | 'light-content';
  tabBarBackground: string;
  tabBarActiveColor: string;
  tabBarInactiveColor: string;
  tabBarBorder: string;
}

export const THEMES: Record<ThemeId, AppTheme> = {
  theme1: {
    id: 'theme1',
    name: 'Soft Blue & Purple',
    isDark: false,
    background: '#F5F7FB',
    bgGradient: ['#D5E7FA', '#FFFFFF'],
    primaryGradient: ['#94BCEB', '#A49EF4'],
    buttonGradient: ['#94BCEB', '#A49EF4'],
    cardBackground: '#FFFFFF',
    primaryText: '#1F2937',
    secondaryText: '#6B7280',
    accent: '#8E95F2',
    border: '#E6E6E6',
    inputBackground: '#FFFFFF',
    statusBar: 'dark-content',
    tabBarBackground: 'rgba(255, 255, 255, 0.82)',
    tabBarActiveColor: '#8E95F2',
    tabBarInactiveColor: '#999999',
    tabBarBorder: 'rgba(255, 255, 255, 0.6)',
  },
  theme2: {
    id: 'theme2',
    name: 'Modern Dark',
    isDark: true,
    background: '#121212',
    bgGradient: ['#1E1E1E', '#121212'],
    primaryGradient: ['#7C3AED', '#5B21B6'],
    buttonGradient: ['#7C3AED', '#5B21B6'],
    cardBackground: '#1E1E1E',
    primaryText: '#FFFFFF',
    secondaryText: '#B3B3B3',
    accent: '#7C3AED',
    border: '#333333',
    inputBackground: '#2D2D2D',
    statusBar: 'light-content',
    tabBarBackground: 'rgba(30, 30, 30, 0.9)',
    tabBarActiveColor: '#7C3AED',
    tabBarInactiveColor: '#666666',
    tabBarBorder: '#2D2D2D',
  },
  theme3: {
    id: 'theme3',
    name: 'Premium Navy',
    isDark: true,
    background: '#0F172A',
    bgGradient: ['#1E293B', '#0F172A'],
    primaryGradient: ['#3B82F6', '#8B5CF6'],
    buttonGradient: ['#3B82F6', '#8B5CF6'],
    cardBackground: '#FFFFFF',
    primaryText: '#0F172A',
    secondaryText: '#475569',
    accent: '#3B82F6',
    border: '#E2E8F0',
    inputBackground: '#F8FAFC',
    statusBar: 'light-content',
    tabBarBackground: 'rgba(255, 255, 255, 0.9)',
    tabBarActiveColor: '#3B82F6',
    tabBarInactiveColor: '#64748B',
    tabBarBorder: '#E2E8F0',
  },
  theme4: {
    id: 'theme4',
    name: 'Mint & Teal',
    isDark: false,
    background: '#F0FDF4',
    bgGradient: ['#E6FBF7', '#FFFFFF'],
    primaryGradient: ['#99F6E4', '#5EEAD4'],
    buttonGradient: ['#5EEAD4', '#2DD4BF'],
    cardBackground: '#FFFFFF',
    primaryText: '#134E4A',
    secondaryText: '#4B5563',
    accent: '#0D9488',
    border: '#CCFBF1',
    inputBackground: '#F0FDF4',
    statusBar: 'dark-content',
    tabBarBackground: 'rgba(255, 255, 255, 0.92)',
    tabBarActiveColor: '#0D9488',
    tabBarInactiveColor: '#94A3B8',
    tabBarBorder: '#CCFBF1',
  },
  theme5: {
    id: 'theme5',
    name: 'Sunset Orange',
    isDark: false,
    background: '#FFF7ED',
    bgGradient: ['#FFEDD5', '#FFFFFF'],
    primaryGradient: ['#FDBA74', '#FB7185'],
    buttonGradient: ['#FDBA74', '#FB7185'],
    cardBackground: '#FFFFFF',
    primaryText: '#7C2D12',
    secondaryText: '#6B7280',
    accent: '#FB7185',
    border: '#FFEDD5',
    inputBackground: '#FFF7ED',
    statusBar: 'dark-content',
    tabBarBackground: 'rgba(255, 255, 255, 0.92)',
    tabBarActiveColor: '#FB7185',
    tabBarInactiveColor: '#9CA3AF',
    tabBarBorder: '#FFEDD5',
  },
  theme6: {
    id: 'theme6',
    name: 'Forest Green',
    isDark: false,
    background: '#F0FDF4',
    bgGradient: ['#DCFCE7', '#FFFFFF'],
    primaryGradient: ['#4ADE80', '#15803D'],
    buttonGradient: ['#4ADE80', '#15803D'],
    cardBackground: '#FFFFFF',
    primaryText: '#14532D',
    secondaryText: '#4F5E53',
    accent: '#16A34A',
    border: '#DCFCE7',
    inputBackground: '#F4FBF7',
    statusBar: 'dark-content',
    tabBarBackground: '#FFFFFF',
    tabBarActiveColor: '#16A34A',
    tabBarInactiveColor: '#8F9E94',
    tabBarBorder: '#DCFCE7',
  },
  theme7: {
    id: 'theme7',
    name: 'Burgundy Rose',
    isDark: false,
    background: '#FFF1F2',
    bgGradient: ['#FFE4E6', '#FFFFFF'],
    primaryGradient: ['#FDA4AF', '#BE123C'],
    buttonGradient: ['#FDA4AF', '#BE123C'],
    cardBackground: '#FFFFFF',
    primaryText: '#881337',
    secondaryText: '#5C6066',
    accent: '#E11D48',
    border: '#FFE4E6',
    inputBackground: '#FFF5F5',
    statusBar: 'dark-content',
    tabBarBackground: '#FFFFFF',
    tabBarActiveColor: '#E11D48',
    tabBarInactiveColor: '#9CA3AF',
    tabBarBorder: '#FFE4E6',
  },
  theme8: {
    id: 'theme8',
    name: 'Midnight Gold',
    isDark: true,
    background: '#0B0F19',
    bgGradient: ['#111827', '#0B0F19'],
    primaryGradient: ['#F59E0B', '#D97706'],
    buttonGradient: ['#F59E0B', '#D97706'],
    cardBackground: '#161F30',
    primaryText: '#FFFFFF',
    secondaryText: '#9CA3AF',
    accent: '#F59E0B',
    border: '#1E293B',
    inputBackground: '#1F2937',
    statusBar: 'light-content',
    tabBarBackground: '#161F30',
    tabBarActiveColor: '#F59E0B',
    tabBarInactiveColor: '#4B5563',
    tabBarBorder: '#1E293B',
  },
  theme9: {
    id: 'theme9',
    name: 'Lavender Mist',
    isDark: false,
    background: '#FAF5FF',
    bgGradient: ['#F3E8FF', '#FFFFFF'],
    primaryGradient: ['#D8B4FE', '#C084FC'],
    buttonGradient: ['#D8B4FE', '#C084FC'],
    cardBackground: '#FFFFFF',
    primaryText: '#581C87',
    secondaryText: '#6B7280',
    accent: '#A855F7',
    border: '#F3E8FF',
    inputBackground: '#FAF5FF',
    statusBar: 'dark-content',
    tabBarBackground: '#FFFFFF',
    tabBarActiveColor: '#A855F7',
    tabBarInactiveColor: '#9CA3AF',
    tabBarBorder: '#F3E8FF',
  },
  theme10: {
    id: 'theme10',
    name: 'Cyberpunk Neon',
    isDark: true,
    background: '#05050A',
    bgGradient: ['#0D0D1F', '#05050A'],
    primaryGradient: ['#EC4899', '#8B5CF6'],
    buttonGradient: ['#EC4899', '#8B5CF6'],
    cardBackground: '#101026',
    primaryText: '#00FFFF',
    secondaryText: '#E5E7EB',
    accent: '#EC4899',
    border: '#1F1F45',
    inputBackground: '#181838',
    statusBar: 'light-content',
    tabBarBackground: '#101026',
    tabBarActiveColor: '#EC4899',
    tabBarInactiveColor: '#4B5563',
    tabBarBorder: '#1F1F45',
  },
  theme11: {
    id: 'theme11',
    name: 'Peach Cream',
    isDark: false,
    background: '#FFFDF9',
    bgGradient: ['#FFEDD5', '#FFFFFF'],
    primaryGradient: ['#FFD8A8', '#FFA94D'],
    buttonGradient: ['#FFD8A8', '#FFA94D'],
    cardBackground: '#FFFFFF',
    primaryText: '#4338CA',
    secondaryText: '#868E96',
    accent: '#E8590C',
    border: '#FFE3E3',
    inputBackground: '#FFF9DB',
    statusBar: 'dark-content',
    tabBarBackground: '#FFFFFF',
    tabBarActiveColor: '#E8590C',
    tabBarInactiveColor: '#A1A8B0',
    tabBarBorder: '#FFE3E3',
  },
  theme12: {
    id: 'theme12',
    name: 'Steel Gray',
    isDark: false,
    background: '#F8F9FA',
    bgGradient: ['#E9ECEF', '#FFFFFF'],
    primaryGradient: ['#CED4DA', '#ADB5BD'],
    buttonGradient: ['#CED4DA', '#ADB5BD'],
    cardBackground: '#FFFFFF',
    primaryText: '#212529',
    secondaryText: '#495057',
    accent: '#495057',
    border: '#DEE2E6',
    inputBackground: '#F1F3F5',
    statusBar: 'dark-content',
    tabBarBackground: '#FFFFFF',
    tabBarActiveColor: '#212529',
    tabBarInactiveColor: '#ADB5BD',
    tabBarBorder: '#DEE2E6',
  },
  theme13: {
    id: 'theme13',
    name: 'Crimson Dusk',
    isDark: true,
    background: '#1F0B0B',
    bgGradient: ['#2D1414', '#1F0B0B'],
    primaryGradient: ['#EF4444', '#991B1B'],
    buttonGradient: ['#EF4444', '#991B1B'],
    cardBackground: '#2D1414',
    primaryText: '#FFFFFF',
    secondaryText: '#D1D5DB',
    accent: '#EF4444',
    border: '#421D1D',
    inputBackground: '#3D1D1D',
    statusBar: 'light-content',
    tabBarBackground: '#2D1414',
    tabBarActiveColor: '#EF4444',
    tabBarInactiveColor: '#6B7280',
    tabBarBorder: '#421D1D',
  },
  theme14: {
    id: 'theme14',
    name: 'Sakura Pink',
    isDark: false,
    background: '#FFF5F7',
    bgGradient: ['#FFE3E8', '#FFFFFF'],
    primaryGradient: ['#FFB7C5', '#FFA1B2'],
    buttonGradient: ['#FFB7C5', '#FFA1B2'],
    cardBackground: '#FFFFFF',
    primaryText: '#9E0031',
    secondaryText: '#666F75',
    accent: '#FF6B8B',
    border: '#FFE3E8',
    inputBackground: '#FFF0F3',
    statusBar: 'dark-content',
    tabBarBackground: '#FFFFFF',
    tabBarActiveColor: '#FF6B8B',
    tabBarInactiveColor: '#A5B1B8',
    tabBarBorder: '#FFE3E8',
  },
  theme15: {
    id: 'theme15',
    name: 'Emerald Royal',
    isDark: true,
    background: '#042012',
    bgGradient: ['#09331D', '#042012'],
    primaryGradient: ['#10B981', '#065F46'],
    buttonGradient: ['#10B981', '#065F46'],
    cardBackground: '#09331D',
    primaryText: '#FFFFFF',
    secondaryText: '#A7F3D0',
    accent: '#10B981',
    border: '#0F4C2D',
    inputBackground: '#0F5E38',
    statusBar: 'light-content',
    tabBarBackground: '#09331D',
    tabBarActiveColor: '#10B981',
    tabBarInactiveColor: '#064E3B',
    tabBarBorder: '#0F4C2D',
  },
  theme16: {
    id: 'theme16',
    name: 'Ocean Breeze',
    isDark: false,
    background: '#F0F9FF',
    bgGradient: ['#E0F2FE', '#FFFFFF'],
    primaryGradient: ['#7DD3FC', '#0EA5E9'],
    buttonGradient: ['#7DD3FC', '#0EA5E9'],
    cardBackground: '#FFFFFF',
    primaryText: '#0369A1',
    secondaryText: '#4B5563',
    accent: '#0284C7',
    border: '#E0F2FE',
    inputBackground: '#F0F9FF',
    statusBar: 'dark-content',
    tabBarBackground: '#FFFFFF',
    tabBarActiveColor: '#0284C7',
    tabBarInactiveColor: '#94A3B8',
    tabBarBorder: '#E0F2FE',
  },
  theme17: {
    id: 'theme17',
    name: 'Coffee & Cream',
    isDark: false,
    background: '#FAF7F2',
    bgGradient: ['#F3ECE0', '#FFFFFF'],
    primaryGradient: ['#C7A37C', '#8C6239'],
    buttonGradient: ['#C7A37C', '#8C6239'],
    cardBackground: '#FFFFFF',
    primaryText: '#4E3629',
    secondaryText: '#6E645E',
    accent: '#8C6239',
    border: '#F3ECE0',
    inputBackground: '#FAF7F2',
    statusBar: 'dark-content',
    tabBarBackground: '#FFFFFF',
    tabBarActiveColor: '#8C6239',
    tabBarInactiveColor: '#B3A59E',
    tabBarBorder: '#F3ECE0',
  },
  theme18: {
    id: 'theme18',
    name: 'Charcoal Minimal',
    isDark: true,
    background: '#1C1917',
    bgGradient: ['#292524', '#1C1917'],
    primaryGradient: ['#78716C', '#44403C'],
    buttonGradient: ['#78716C', '#44403C'],
    cardBackground: '#292524',
    primaryText: '#F5F5F4',
    secondaryText: '#A8A29E',
    accent: '#78716C',
    border: '#3E3A37',
    inputBackground: '#3E3A37',
    statusBar: 'light-content',
    tabBarBackground: '#292524',
    tabBarActiveColor: '#F5F5F4',
    tabBarInactiveColor: '#57534E',
    tabBarBorder: '#3E3A37',
  },
  theme19: {
    id: 'theme19',
    name: 'Electric Violet',
    isDark: true,
    background: '#0F0A1C',
    bgGradient: ['#181132', '#0F0A1C'],
    primaryGradient: ['#8B5CF6', '#4C1D95'],
    buttonGradient: ['#8B5CF6', '#4C1D95'],
    cardBackground: '#181132',
    primaryText: '#F5F3FF',
    secondaryText: '#DDD6FE',
    accent: '#8B5CF6',
    border: '#2E2254',
    inputBackground: '#271C46',
    statusBar: 'light-content',
    tabBarBackground: '#181132',
    tabBarActiveColor: '#8B5CF6',
    tabBarInactiveColor: '#4C1D95',
    tabBarBorder: '#2E2254',
  },
  theme20: {
    id: 'theme20',
    name: 'Sand & Bronze',
    isDark: false,
    background: '#FCFBFA',
    bgGradient: ['#F5F0E6', '#FFFFFF'],
    primaryGradient: ['#E3C79A', '#CD8B37'],
    buttonGradient: ['#E3C79A', '#CD8B37'],
    cardBackground: '#FFFFFF',
    primaryText: '#5C3E14',
    secondaryText: '#7A6E5D',
    accent: '#CD8B37',
    border: '#F5F0E6',
    inputBackground: '#FCFBFA',
    statusBar: 'dark-content',
    tabBarBackground: '#FFFFFF',
    tabBarActiveColor: '#CD8B37',
    tabBarInactiveColor: '#BFAFA0',
    tabBarBorder: '#F5F0E6',
  },
};
